import type { Metadata } from "next";
import Link from "next/link";
import { AdSlot } from "@/components/AdSlot";
import { LastUpdated } from "@/components/LastUpdated";
import { TicketPnrIllustration } from "@/components/TicketPnrIllustration";
import { RouteLineDivider } from "@/components/RouteLineDivider";

const SITE_URL = "https://trackmypnr.co.in";
const OG_IMAGE = `${SITE_URL}/og-default.png`;
const PAGE_URL = `${SITE_URL}/pnr-status-guide`;

export const metadata: Metadata = {
  title: "PNR Status Guide: What It Means & How to Check It",
  description:
    "A complete guide to your Indian Railways PNR number — what it is, where to find it, what chart preparation means, and how to read every status: CNF, RAC, and WL.",
  alternates: { canonical: "/pnr-status-guide" },
  robots: { index: true, follow: true },
  openGraph: {
    title: "PNR Status Guide: What It Means & How to Check It",
    description:
      "What a PNR is, where to find it, what chart preparation means, and how to read every status.",
    url: "/pnr-status-guide",
    images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: "PNR Status Guide — trackmypnr" }],
  },
  twitter: {
    card: "summary_large_image",
    images: [OG_IMAGE],
  },
};

const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: SITE_URL },
    { "@type": "ListItem", position: 2, name: "PNR Status Guide", item: PAGE_URL },
  ],
};

const articleJsonLd = {
  "@context": "https://schema.org",
  "@type": "Article",
  headline: "PNR Status Guide: What It Means and How to Check It",
  description:
    "A complete guide to your Indian Railways PNR number — what it is, where to find it, what chart preparation means, and how to read every status: CNF, RAC, and WL.",
  url: PAGE_URL,
  datePublished: "2026-08-01",
  dateModified: "2026-08-01",
  author: { "@type": "Organization", name: "trackmypnr", url: SITE_URL },
  publisher: {
    "@type": "Organization",
    name: "trackmypnr",
    url: SITE_URL,
    logo: { "@type": "ImageObject", url: `${SITE_URL}/logo.png` },
  },
  image: OG_IMAGE,
  mainEntityOfPage: { "@type": "WebPage", "@id": PAGE_URL },
};

export default function PnrStatusGuidePage() {
  return (
    <article className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }}
      />

      <nav aria-label="Breadcrumb" className="mb-6 text-sm text-ink-muted">
        <ol className="flex items-center gap-1.5">
          <li><Link href="/" className="hover:text-brand">Home</Link></li>
          <li aria-hidden="true">›</li>
          <li aria-current="page" className="text-ink">PNR Status Guide</li>
        </ol>
      </nav>

      <h1 className="font-display text-3xl font-bold text-ink sm:text-4xl">
        PNR Status Guide: What It Means and How to Check It
      </h1>
      <div className="mt-3">
        <LastUpdated date="2026-08-01" />
      </div>

      <p className="mt-6 text-lg leading-relaxed text-ink-muted">
        If you&apos;ve booked a train ticket on Indian Railways, you&apos;ve got a PNR number —
        and understanding what it tells you can save you a lot of last-minute stress. This guide
        covers what a PNR actually is, where to find it, and exactly what each status on your
        ticket means.
      </p>

      <h2 className="mt-10 font-display text-2xl font-bold text-ink">What Is a PNR Number?</h2>
      <p className="mt-3 leading-relaxed text-ink-muted">
        PNR stands for Passenger Name Record. It&apos;s a unique 10-digit reference number
        generated by Indian Railways&apos; reservation system the moment you book a ticket,
        whether through IRCTC&apos;s website, the app, or a railway counter. It links your
        specific booking — passenger details, train, coach, seat or berth, and journey date —
        to a single record that the system can look up at any time. Whenever you want to{" "}
        <Link href="/" className="font-medium text-brand underline">
          check your PNR status
        </Link>
        , this 10-digit number is the only thing you need.
      </p>

      <h2 className="mt-10 font-display text-2xl font-bold text-ink">Where to Find Your PNR</h2>
      <p className="mt-3 leading-relaxed text-ink-muted">
        Your PNR is printed at the top of your ticket, whether it&apos;s a physical
        counter-issued ticket or an e-ticket PDF. On an SMS booking confirmation, it&apos;s
        usually the first 10-digit number mentioned. It&apos;s separate from your train number
        (which is usually 5 digits) — the two are easy to mix up if you&apos;re booking in a
        hurry.
      </p>
      <div className="mt-6 flex justify-center">
        <TicketPnrIllustration />
      </div>

      <h2 className="mt-10 font-display text-2xl font-bold text-ink">
        Do the Digits in a PNR Mean Anything?
      </h2>
      <p className="mt-3 leading-relaxed text-ink-muted">
        A lot of articles claim you can &ldquo;decode&rdquo; a PNR — that specific digits reveal
        your booking zone, quota, or train type just by reading the number. In practice, this
        isn&apos;t reliable: Indian Railways doesn&apos;t publish a documented scheme mapping
        PNR digits to journey details, and the number functions as an internal reservation
        reference rather than an encoded message. The genuinely useful information — your train,
        route, class, and passenger status — is stored against the PNR in IRCTC&apos;s system,
        not embedded in the digits themselves. That&apos;s exactly why a PNR status checker
        exists: to pull that real record instead of guessing at it.
      </p>

      <RouteLineDivider className="my-10" />

      <h2 className="mt-2 font-display text-2xl font-bold text-ink">
        Understanding Chart Preparation
      </h2>
      <p className="mt-3 leading-relaxed text-ink-muted">
        &ldquo;Chart preparation&rdquo; is when Indian Railways finalizes the passenger list for
        a train — allocating confirmed berths, processing RAC and waitlist movements, and
        locking in the seating chart that gets posted at the station and on the coach door. This
        typically happens <strong>3 to 4 hours before the train&apos;s scheduled departure</strong>{" "}
        from its originating station (for trains departing from an intermediate station, the
        first chart is often prepared 4-8 hours earlier still, with a second chart closer to
        departure). Practically, this matters because:
      </p>
      <ul className="mt-3 list-disc space-y-2 pl-6 leading-relaxed text-ink-muted">
        <li>
          Before chart preparation, your waitlist or RAC position can still improve as other
          passengers cancel.
        </li>
        <li>
          After chart preparation, your status is effectively final for that journey — if
          you&apos;re still fully waitlisted at this point, you will not be able to board (see
          the refund note below).
        </li>
        <li>
          Tatkal and premium quota seats are also finalized at this point, so it&apos;s the last
          meaningful moment for a status change.
        </li>
      </ul>

      <h2 className="mt-10 font-display text-2xl font-bold text-ink">
        Reading Your Status: CNF, RAC, and WL
      </h2>
      <p className="mt-3 leading-relaxed text-ink-muted">
        Every passenger on a PNR gets one of three broad statuses:
      </p>
      <ul className="mt-3 list-disc space-y-2 pl-6 leading-relaxed text-ink-muted">
        <li>
          <strong>CNF (Confirmed)</strong> — you have an allocated coach and berth number. This
          is final and won&apos;t change unless you or Railways make a manual modification.
        </li>
        <li>
          <strong>RAC (Reservation Against Cancellation)</strong> — you&apos;re guaranteed to
          board and will share a berth with another RAC passenger, with a real chance of
          upgrading to a full CNF berth as cancellations come in before chart preparation.
        </li>
        <li>
          <strong>WL (Waitlisted)</strong> — you don&apos;t have a berth yet. There are several
          waitlist sub-types (GNWL, TQWL, RLWL, PQWL, and more), each with different odds of
          clearing — see our{" "}
          <Link href="/waitlist-types" className="font-medium text-brand underline">
            full waitlist types guide
          </Link>{" "}
          for a breakdown of each one.
        </li>
      </ul>
      <p className="mt-3 leading-relaxed text-ink-muted">
        For RAC and waitlisted tickets, our{" "}
        <Link href="/" className="font-medium text-brand underline">
          PNR checker
        </Link>{" "}
        shows a confirmation probability estimate alongside the raw status, so you get a sense of
        your real odds instead of just a label.
      </p>

      <h2 className="mt-10 font-display text-2xl font-bold text-ink">How Long Is a PNR Valid?</h2>
      <p className="mt-3 leading-relaxed text-ink-muted">
        A PNR remains valid and checkable for <strong>9 months from the date of booking</strong>.
        After that window, the record ages out of the active lookup system. If you need
        historical proof of an old journey beyond that period, you&apos;d need to request it
        directly from IRCTC rather than through a standard status check.
      </p>

      <h2 className="mt-10 font-display text-2xl font-bold text-ink">
        What Happens If You&apos;re Still Waitlisted After Chart Preparation?
      </h2>
      <p className="mt-3 leading-relaxed text-ink-muted">
        If your ticket is booked against the regular quota and remains fully waitlisted (not
        even RAC) once the chart is prepared, you are not permitted to board the train with that
        ticket, and IRCTC processes an automatic refund — usually the full fare minus applicable
        cancellation charges, credited back to your original payment method within a few
        business days. This is handled automatically for online (e-ticket) bookings; you don&apos;t
        need to file anything yourself. Our{" "}
        <Link href="/faq" className="font-medium text-brand underline">
          FAQ page
        </Link>{" "}
        covers the related TDR (Ticket Deposit Receipt) process for edge cases like partially
        confirmed group bookings.
      </p>

      <AdSlot slotId="pnr-status-guide-mid-content" className="my-10" />

      <h2 className="mt-2 font-display text-2xl font-bold text-ink">Checking Your Status</h2>
      <p className="mt-3 leading-relaxed text-ink-muted">
        Once you have your 10-digit PNR in hand, checking it takes seconds.{" "}
        <Link href="/" className="font-medium text-brand underline">
          Head to the trackmypnr homepage
        </Link>
        , enter your number, and you&apos;ll see your live status, chart preparation state, and —
        if you&apos;re RAC or waitlisted — a clear confirmation probability estimate. You can
        also save the PNR to revisit later and see how its status has changed over time.
      </p>

      <RouteLineDivider className="my-10" />
      <p className="text-sm text-ink-muted">
        Related reading:{" "}
        <Link href="/waitlist-types" className="font-medium text-brand underline">
          Waitlist Types Explained
        </Link>{" "}
        ·{" "}
        <Link href="/travel-classes" className="font-medium text-brand underline">
          Travel Classes Breakdown
        </Link>{" "}
        ·{" "}
        <Link href="/faq" className="font-medium text-brand underline">
          Frequently Asked Questions
        </Link>{" "}
        ·{" "}
        <Link href="/about" className="font-medium text-brand underline">
          About Us
        </Link>
      </p>
    </article>
  );
}
